version: "3"

services:
  judgernode-java:
    build:
      context: ./rce-judger-nodes
      dockerfile: Dockerfile
      target: java
    env_file:
      - ./rce-judger-nodes/.env.local
    environment: 
      - LANG=java
    restart: on-failure